// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package GraphQLdemo

type Film struct {
	ID           string  `json:"id"`
	Title        string  `json:"title"`
	EpisodeID    *int    `json:"episode_id"`
	OpeningCrawl *string `json:"opening_crawl"`
	Director     *string `json:"director"`
	Producer     *string `json:"producer"`
	ReleaseDate  *string `json:"release_date"`
}

type FilmConnection struct {
	PageInfo   PageInfo   `json:"pageInfo"`
	Edges      []FilmEdge `json:"edges"`
	TotalCount int        `json:"totalCount"`
}

type FilmEdge struct {
	Node   *Film  `json:"node"`
	Cursor string `json:"cursor"`
}

type PageInfo struct {
	HasNextPage     bool   `json:"hasNextPage"`
	HasPreviousPage bool   `json:"hasPreviousPage"`
	StartCursor     string `json:"startCursor"`
	EndCursor       string `json:"endCursor"`
}

type PeopleConnection struct {
	PageInfo   PageInfo     `json:"pageInfo"`
	Edges      []PeopleEdge `json:"edges"`
	TotalCount int          `json:"totalCount"`
}

type PeopleEdge struct {
	Node   *People `json:"node"`
	Cursor string  `json:"cursor"`
}
